FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.24.5@sha256:ef5b4be1f94b36c90385abd9b6b4f201723ae28e71acacb76d00687333c17282 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.22@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-matrix"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-matrix"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-matrix"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-matrix"

COPY --from=build /src/dist/wp-matrix /bin/wp-matrix
ENTRYPOINT [ "/bin/wp-matrix" ]
